네비게이션 뷰에 custom 백버튼을 적용
DeveloperAcademy-POSTECH/toGather pull request #116
Opened 2022-07-20 08:33 UTC by limhyoseok

비트 @yeongwooCho 랜스 @limhyoseok 밀러 @KimDaeSeong8721 닐 @yudonlee 맥스 @Sungwooo 이브@unuhqueen

## 🍏 관련 이슈

## 🍏 작업내용

커스텀 백버튼을 바로 사용할 수 있는 CustomNavigationLnik 구현

![Simulator Screen Recording - iPhone 13 - 2022-07-20 at 16 57 43](https://user-images.githubusercontent.com/59302419/179936256-ae78e63a-a01c-499e-a452-8d6362fb9f6d.gif)

사용법은 NavigationLink와 동일

<img width="826" alt="image" src="https://user-images.githubusercontent.com/59302419/179936158-4eaa9054-0025-4dd5-956c-790d26da6708.png">

## 🍏 리뷰포인트

## 🍏 다음으로 진행될 작업
 - [ ] 다음으로 할 일을 적어주세요.

## 🍏 질문

## 🍏 주의사항
- **빈 폴더 있는지 확인하기!!**

2022-07-20 11:56 UTC, KimDaeSeong8721 approved these changes
이해하기가 어렵네요 😂. 요약하면 생성자 두개로 나눠놓은 이유가  세번째페이지뷰에서 종료버튼 눌렀을때 두번째뷰,세번째뷰를 모두 닫아버리게 하기위해서라고 이해하면 될까여. 닐의 isPresentedMode와 유사하네여

2022-07-20 23:47 UTC, limhyoseok commented on ToGather/ToGather/Global/Service/CustomNavigationLink.swift
> +struct CustomNavigationLink<DestinationView, ContentView>: View where ContentView: View, DestinationView: View {
where의 사용 용도는 <DestinationView, ContentView> 안에 있는 것들의 protocol이 어떤 것인지 알려주는 용도라고 이해하시면 될 것 같습니다. 저게 있어야 view protocol을 따르는 다양한 view들을 DestinationView, ContentView의 인자로 받을 수 있습니다.

람다식은 어떤 것을 말하는 거죵?

2022-07-20 23:51 UTC, limhyoseok commented
@KimDaeSeong8721 
실제 NavigationLink도 init이 여러개이더라고요
기존에는 destination, label만 받는 init을 썼지만, neal이 사용한 isActive를 포함한 NavigationLink에 대응하기 위해서 생성자를 두개 받았습니다. ( NavigationLink에서 isActive 용도는 isActive를 false로 변경시키면 열렸던 네비게이션 뷰들을 모두 닫아버립니다)

사실 isActive에 디폴트값을 받게하면 init하나로 해결할 수 있겠지만 타입이 Binding<Bool>이라 처리하기가 쉽지 않아서 init을 두개로 분리한 이유도 있습니다

2022-07-21 02:03 UTC, yudonlee requested changes
주석만 삭제하시면 완벽할 것 같습니다~ 
핸들러를 사용해서 동일한 NavigationLink의 action, label 구조를 그대로 썼기 때문에 기존의 코드를 바꾸지 않았다는 점 잘 배웠습니다!

2022-07-21 02:03 UTC, yudonlee commented on ToGather/ToGather/Global/Service/CustomNavigationLink.swift
> +            }
해당 링크는 GoalSetting.swift에서 적용되는 것이네요! 
isActive라는 Binding variable을 true로 만들어주고 모달을 띄우는 형태이군요
클로저를 잘 사용해서 NavigationLink의 커스텀을 만들어둔게 인상깊습니다.. 진짜 👍

2022-07-21 23:51 UTC, yudonlee approved these changes

2022-07-25 13:35 UTC, merged