Feat/128 disable next button
DeveloperAcademy-POSTECH/toGather pull request #129
Opened 2022-07-27 01:34 UTC by limhyoseok

## 🍏 작업내용
<img width="780" alt="image" src="https://user-images.githubusercontent.com/59302419/181141225-3247381b-51a5-4b5b-8e1a-4f423b7c4616.png">

- 아이템 선택하지 않을 경우 다음 버튼 비활성화 (아래 뷰에 적용)
    - GoalSetting
    - SettingPeriod
    - FriendAdditionView
- SettingPeriod.swift에서 코드 들여쓰기 재정렬

## 🍏 다음으로 진행될 작업
 - [ ] 다음으로 할 일을 적어주세요.

## 🍏 질문

2022-07-27 23:51 UTC, yudonlee requested changes
수고하셨습니다!

2022-07-27 23:51 UTC, yudonlee commented on ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
> +                .disabled(friendAdditionViewModel.isFriendEmpty())
우리 친구추가뷰에서는 버튼 비활성화 안해주기로 했던거 아니였나요? 키보드로 가려버려서 괜찮다고 했었어요!

2022-07-28 04:08 UTC, yudonlee approved these changes

2022-07-28 04:19 UTC, limhyoseok commented on ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
> +                .disabled(friendAdditionViewModel.isFriendEmpty())
변경했습니다!

2022-07-28 05:03 UTC, KimDaeSeong8721 approved these changes
수고하셨습니다!

2022-07-28 05:06 UTC, merged